{{- if .Values.extensions.enabled }}
{{- range .Values.extensions.items }}
apiVersion: ai-platform.suse.com/v1alpha1
kind: InstallAIExtension
metadata:
  name: {{ .name }}
spec:
  helm:
    name: {{ .helm.name }}
    url: {{ .helm.url }}
    version: {{ .helm.version }}
    type: {{ .helm.type }}
  extension:
    name: {{ .name }}
    version: {{ .version }}
---
{{- end }}
{{- end }}
