{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "suse-ai-operator.labels" . | nindent 4 }}
  name: {{ include "suse-ai-operator.serviceName" (dict "context" . "suffix" "metrics") }}
spec:
  ports:
    - name: https
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "suse-ai-operator.selectorLabels" . | nindent 4 }}
{{- end }}
