annotations:
  helm.sh/images: |
    - image: ghcr.io/suse/suse-ai-lifecycle-manager:1.0.0
      name: suse-ai-lifecycle-manager
  license: Apache-2.0
apiVersion: v2
name: suse-ai-lifecycle-manager
version: 1.0.0
description: SUSE AI Rancher UI Extension
type: application
keywords:
  - rancher
  - extension
  - ai
home: https://github.com/SUSE/suse-ai-lifecycle-manager
icon: https://github.com/SUSE/suse-ai-lifecycle-manager/blob/main/pkg/suse-ai-lifecycle-manager/assets/logo.svg
sources:
  - https://github.com/SUSE/suse-ai-lifecycle-manager
appVersion: 1.0.0
maintainers:
  - url: https://www.suse.com/
    name: SUSE LLC
