{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "suse-ai-operator.labels" . | nindent 4 }}
  name: {{ include "suse-ai-operator.serviceName" (dict "context" . "suffix" "installaiextension-viewer") }}
rules:
  - apiGroups:
      - ai-platform.suse.com
    resources:
      - installaiextensions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ai-platform.suse.com
    resources:
      - installaiextensions/status
    verbs:
      - get
{{- end }}
