apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "suse-ai-operator.labels" . | nindent 4 }}
  name: {{ include "suse-ai-operator.serviceName" (dict "context" . "suffix" "leader-election") }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "suse-ai-operator.serviceName" (dict "context" . "suffix" "leader-election") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "suse-ai-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
