{{- if .Values.metrics.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "suse-ai-operator.serviceName" (dict "context" . "suffix" "metrics-auth") }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "suse-ai-operator.serviceName" (dict "context" . "suffix" "metrics-auth") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "suse-ai-operator.fullname" . }}
{{- end }}
