name: Create Tag and Release Code

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  create_tag_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get pkg version
        id: pkg_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          APP_NAME=$(jq -r '.name' package.json | sed 's/@//;s/\///g')
          echo "app_tag=${APP_NAME}-${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Create Tag
        id: create_tag
        run: |
          git tag ${{ steps.pkg_version.outputs.app_tag }}
          git push origin ${{ steps.pkg_version.outputs.app_tag }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.pkg_version.outputs.app_tag }}
          name: ${{ steps.pkg_version.outputs.app_tag }}
          body: |
            Release created automatically by GitHub Actions.
          draft: false

      - name: Trigger Container Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"build_container","client_payload":{"tag":"${{ steps.pkg_version.outputs.app_tag }}"}}'
