name: Release SUSE AI Operator [Container and Helm Chart]

on:
  push:
    branches:
      - main
    tags:
      - suse-ai-operator-*

env:
    CONTAINER_REGISTRY: ghcr.io/leooamaral/suse-ai-operator
    CHART_PATH: deploy/charts/suse-ai-operator
    CHART_REGISTRY: oci://ghcr.io/leooamaral/chart
jobs:
  container:
    outputs:
      VERSION: ${{ steps.tags.outputs.VERSION }}
      CHART_VERSION: ${{ steps.tags.outputs.CHART_VERSION }}
      PUBLISH: ${{ steps.tags.outputs.PUBLISH }}
      METADATA_TAGS: ${{ steps.tags.outputs.METADATA_TAGS }}
      NOTES_START_TAG: ${{ steps.tags.outputs.NOTES_START_TAG }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calculate tags
        id: tags
        shell: bash
        run: |
          ref=${{ github.ref }}
          case "$ref" in
            refs/heads/main)
              BASE_VERSION=$(cat VERSION)
              
              git fetch --tags

              LAST_DEV=$(git tag \
                --list "suse-ai-operator-${BASE_VERSION}-dev.*" \
                --sort=-v:refname \
                | head -n 1)

              if [[ -z "$LAST_DEV" ]]; then
                DEV_NUM=1
                NOTES_START_TAG=$(git tag --list "suse-ai-operator-*" --sort=-v:refname | grep -v "\-dev" | head -n 1)
              else
                DEV_NUM="${LAST_DEV##*.}"
                DEV_NUM=$((DEV_NUM + 1))
                NOTES_START_TAG="$LAST_DEV"
              fi

              VERSION="${BASE_VERSION}-dev.${DEV_NUM}"
              IMAGE_TAGS="$VERSION"
              CHART_VERSION="$VERSION"

              {
                echo "METADATA_TAGS<<EOF"
                echo "$VERSION"
                echo "EOF"
              } >> "$GITHUB_OUTPUT"

              PUBLISH=true
              ;;
            refs/tags/suse-ai-operator-*)
              VERSION="${ref#refs/tags/suse-ai-operator-}"
              IMAGE_TAGS="$VERSION"
              CHART_VERSION="$VERSION"
              NOTES_START_TAG=""

              {
                echo "METADATA_TAGS<<EOF"
                echo "$VERSION"
                if [[ "$VERSION" != *"-"* ]]; then
                  echo "latest"
                fi
                echo "EOF"
              } >> "$GITHUB_OUTPUT"

              PUBLISH=true
              ;;
            *)
              VERSION="${{ github.sha }}"
              IMAGE_TAGS="$VERSION"
              CHART_VERSION="$VERSION"
              NOTES_START_TAG=""

              {
                echo "METADATA_TAGS<<EOF"
                echo "$VERSION"
                echo "EOF"
              } >> "$GITHUB_OUTPUT"

              PUBLISH=false
              ;;
          esac

          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "IMAGE_TAGS=$IMAGE_TAGS" >> "$GITHUB_OUTPUT"
          echo "PUBLISH=$PUBLISH" >> "$GITHUB_OUTPUT"
          echo "CHART_VERSION=$CHART_VERSION" >> "$GITHUB_OUTPUT"
          echo "NOTES_START_TAG=$NOTES_START_TAG" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        if: steps.tags.outputs.PUBLISH == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        if: steps.tags.outputs.PUBLISH == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        if: steps.tags.outputs.PUBLISH == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Get Docker Metadata
        id: meta
        if: steps.tags.outputs.PUBLISH == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}
          tags: |
            ${{ steps.tags.outputs.METADATA_TAGS }}

      - name: Build Docker Container
        id: push
        if: steps.tags.outputs.PUBLISH == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: linux/arm64,linux/amd64

  helm:
    needs: container
    if: needs.container.outputs.PUBLISH == 'true'
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Chart.yaml
        run: |
          yq -i '.version = "${{ needs.container.outputs.CHART_VERSION }}"' $CHART_PATH/Chart.yaml
          yq -i '.appVersion = "${{ needs.container.outputs.VERSION }}"' $CHART_PATH/Chart.yaml

      - name: Update image annotations
        run: |
          yq -i '
            .annotations."helm.sh/images" =
            "- image: ghcr.io/leooamaral/suse-ai-operator:${{ needs.container.outputs.VERSION }}\n  name: suse-ai-operator"
          ' $CHART_PATH/Chart.yaml

      - name: Package Helm Chart
        id: package
        run: |
          chart_package=$(helm package $CHART_PATH --destination . | awk '{print $NF}')
          echo "chart_package=$chart_package" >> $GITHUB_OUTPUT

      - name: Publish Helm Chart
        run: |
          helm push ${{ steps.package.outputs.chart_package }} \
            $CHART_REGISTRY

      - name: Create dev git tag
        if: needs.container.outputs.PUBLISH == 'true' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          TAG="suse-ai-operator-${{ needs.container.outputs.VERSION }}"
          git checkout -b release/${TAG}

          git add $CHART_PATH/Chart.yaml
          git commit -m "chore(release): ${TAG}"

          git tag "$TAG"
          git push origin "$TAG"

      - name: Create pre-release and release notes for dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          START_TAG: ${{ needs.container.outputs.NOTES_START_TAG }}
        if: needs.container.outputs.PUBLISH == 'true' && github.ref == 'refs/heads/main'
        run: |
          TAG="suse-ai-operator-${{ needs.container.outputs.VERSION }}"

          NOTES_ARG=""
          if [[ -n "$START_TAG" ]]; then
            NOTES_ARG="--notes-start-tag $START_TAG"
          fi

          gh release create "${TAG}" \
            --title "${TAG}" \
            --prerelease --fail-on-no-commits \
            --generate-notes $NOTES_ARG
